### ISSUE TITLE
need to log in twice in order to log in.

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#157]

**Comment by mingjiecn** [comment]
notes on 10/14/2020: After first sign in, there is a pop up to say thank you for log in but nothing happened. No cohort icon, no my name on top right. after second sign in it will work and sign in button change to sign out button. After that if you log out, you can log back in on the first try without problem

**Comment by vsmalladi** [comment]
Looks to be only localhost.
