### ISSUE TITLE
Update the content in drop down menu Materials & Methods - Assays and standards

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#163]
For assay page will need to mimic this:

https://www.encodeproject.org/data-standards/

Assays we know of:

- [x] WGS

- [x] WES

- [x] RNA-seq

- [x] Methylation

**Comment by vsmalladi** [comment]
I think I updated this. But double check the content.

**Comment by vsmalladi** [comment]
Moving this to version 2.0 Need to get a lockdown on all of the assay actually used.

**Comment by vsmalladi** [comment]
Just a place holder page.
