### ISSUE TITLE
Upgrade to Ubuntu 18 env

### ISSUE THREAD

**Issue by SenseCode** [utsw-bicf/pandiseased#171]

**Comment by vsmalladi** [comment]
Using this readme: https://github.com/ENCODE-DCC/encoded/blob/dev/README.md

**Comment by vsmalladi** [comment]
Works on Azure.

Will move to using apache instead of nginx to see if can load.

**Comment by mingjiecn** [comment]
06/02/2020:  need to update the document regarding installation
