### ISSUE TITLE
Change the css for unselected facets

### ISSUE THREAD

**Issue by cmonnom** [utsw-bicf/pandiseased#188]
Replace this css:
```
.facet-term.negated-selected {
    background-color: #e50400; }
```
by this one:
```
.facet-term.negated-selected > .facet-term__item {
    text-decoration: line-through;
}
```

**Comment by vsmalladi** [comment]
@cmonnom Wouldn't a line through be harder to read what text is select as you scroll?

**Comment by cmonnom** [comment]
I'm also thinking that the red vs blue is not accessible friendly for the selected/not-selected at the top. An easy thing is to change the icon next to them (we can keep the colors).
A check mark for "selected" and the cancel icon for "not-selected".

**Comment by vsmalladi** [comment]
I agree something else for distingtion would be best

**Comment by cmonnom** [comment]
![image](https://user-images.githubusercontent.com/1919424/80140416-86570200-856d-11ea-8f52-db860297f681.png)

That should do it.
