### ISSUE TITLE
switch to UTSW Ldap server

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#19]

**Comment by SenseCode** [comment]
Detailed explanation of the task?

**Comment by vsmalladi** [comment]
Current login is controlled by auth0: https://auth0.com/ and is still linked to encode.autho0.com.

We need to change this so that it used UTSW on premise server: https://auth0.com/docs/connections/enterprise/active-directory-ldap

or maybe Microsoft.

**Comment by vsmalladi** [comment]
Change to microsoft login or local ldap server
