### ISSUE TITLE
Ideas for website design

### ISSUE THREAD

**Issue by SenseCode** [utsw-bicf/pandiseased#21]
![image](https://user-images.githubusercontent.com/38848214/65785563-44bac180-e11a-11e9-92f0-0bde918743d4.png)

**Comment by cmonnom** [comment]
For icons, you should use standard packages like https://fontawesome.com/start or https://materialdesignicons.com/ just to name a few. I think fontawesome is already installed for KCE.

**Comment by vsmalladi** [comment]
Closing issues. These have been resolved.
#65
