### ISSUE TITLE
Prevent submission of nephrectomy details

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#210]
Add the following to prevent submitting of nephrectomy details. 

-  Biopsy

- Excision

- Fine needle aspiration

**Comment by SenseCode** [comment]
Just found old dependencies doesn't work : with Ablation/Met &&nephrectomy_details we can still submit data....I will fix the same time. 
![image](https://user-images.githubusercontent.com/38848214/81465362-47d95e00-918f-11ea-830d-42eb9b8088ea.png)
