### ISSUE TITLE
Radiation missing data

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#218]
There are radiation data historically with missing:
* dose
* fraction
* end_date

Potential fix:
"type": ["number", "null"]

Data examples:

    {
        "site_specific":"Brain",
        "site_general":"Brain",
        "dose":null,
        "dose_units":"cGy",
        "fractions":null,
        "treatment_intention":"Not Available",
        "start_date":"1849-12-21",
        "status":"released"
    },
    {
        "site_specific":"Brain",
        "site_general":"Brain",
        "dose":null,
        "dose_units":"cGy",
        "fractions":null,
        "treatment_intention":"Not Available",
        "start_date":"1858-06-08",
        "status":"released"
    },
   {
        "site_specific":"Brain",
        "site_general":"Brain",
        "dose":null,
        "dose_units":"cGy",
        "fractions":null,
        "treatment_intention":"Not Available",
        "start_date":"1868-05-11",
        "status":"released"
    },

**Comment by mingjiecn** [comment]
Alana will request the missing data for now based on meeting 06/01/2020.

**Comment by vsmalladi** [comment]
Looks like we will have issing data going forward.

**Comment by mingjiecn** [comment]
Will not add null or other value if the data is missing. Will need to modify those calculated fields in patient.py: dose range, fraction range, last follow up date. Will need to modify the required and dependency in radiation schema: dose, fractions, dose unit are depended on each other. Will need to handle missing data display in radiation.js.
