### ISSUE TITLE
Dominant Tumor Calculation

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#221]
Calculated dominat 

1. Highest stage (pT, pN stage)
2. Aggressive histologies (CDC, medullary, FH, ccRCC)
4. Within same stage, size of tumor

**Comment by vsmalladi** [comment]
Histology aggresive ranking:

- Aggresive:
1. Collecting duct carcinoma
2. Renal medullary carcinoma
3.  Hereditary leiomyomatosis and renal cell carcinoma-associated renal cell carcinoma
- ccRCC:
4. Clear cell renal cell carcinoma
5.  Renal cell carcinoma, unclassified
- Similar perhaps to ccRCC:
6. Papillary renal cell carcinoma, Type 2.
7. MiT family translocation renal cell carcinoma
8. Xp11 translocation renal cell carcinoma
9. t(6;11) renal cell carcinoma
10. Tubulocystic renal cell carcinoma
- Better survival than ccRCC:
11. Papillary renal cell carcinoma
12. Papillary renal cell carcinoma, Type 1
13. Mucinous tubular and spindle renal cell carcinoma
14. Acquired cystic disease associated renal cell carcinoma
15. Succinate dehydrogenase (SDH) deficient renal cell carcinoma
- Less frequency metastasize:
16. Chromophobe renal cell carcinoma
- Less aggressive- green— do not metastasize:
17. Multilocular cystic clear cell renal cell neoplasm of low malignant potential
18. Clear cell papillary renal cell carcinoma

**Comment by mingjiecn** [comment]
for stage comparison, we will use t_stage and n_stage for comparison after discussing with @vsmalladi on 10/27/2020

**Comment by mingjiecn** [comment]
pT ranking: "Not applicable" < "pTX" <"pT1" = ("pT1a" <"pT1b") < "pT2" = ("pT2a" <"pT2b") < "pT3" = ("pT3a" < "pT3b" < "pT3c") < "pT4",
pN ranking: "Not applicable", <  "Not available" = "pNX" <"pN0" < "pN1" < "pN2",

**Comment by mingjiecn** [comment]
Histology schema enums are not matching the histology ranking list above: 
                "Acquired cystic disease-associated RCC" =  **14 Acquired cystic disease associated renal cell carcinoma**
                "Angiomyolipoma",
                "ccPRCC" = **18 Clear cell papillary renal cell carcinoma**
                "ccRCC" = **4 Clear cell renal cell carcinoma**
                "ChRCC" = **16 Chromophobe renal cell carcinoma**
                "ChRCC, hybrid type",
                "collecting duct carcinoma(CDC)" = **1 Collecting duct carcinoma**
                "Cystic nephroma",
                "HLRCC",
                "Leiomyoma",
                "Leiomyosarcoma",
                "Metanephric adenoma",
                "Mucinous tubular and spindle cell carcinoma" = **13 Mucinous tubular and spindle renal cell carcinoma**
                "multilocular cystic renal neoplasm of low malignant potential" = **17 Multilocular cystic clear cell renal cell neoplasm of low malignant potential**
                "PRCC, no type given" = **11 Papillary renal cell carcinoma**
                "PRCC, type 1" = **12 Papillary renal cell carcinoma, Type 1**
                "PRCC, type 2" = **6 Papillary renal cell carcinoma, Type 2.**
                "Poorly differentiated malignancy",
                "Renal medullary carcinoma" = **2 Renal medullary carcinoma**
                "Renal Cell Carcinoma, NOS" = **5 Renal cell carcinoma, unclassified**
                "RO",
                "RON",
                "RON, favor ChRCC",
                "RON, favor RO",
                "Sarcomatoid, NOS",
                "Sarcoma",
                "MiT family translocation RCC" = **7 MiT family translocation renal cell carcinoma**
                "Tubulocystic RCC" = **10 Tubulocystic renal cell carcinoma**
                "Unclassified" = **5 Renal cell carcinoma, unclassified**
                "Unclassified RCC" = **5 Renal cell carcinoma, unclassified**
                "Nephroblastoma (Wilms tumor)",
                "Soft tissue neoplasm, NOS",
                "SDH deficient RCC" = **15 Succinate dehydrogenase (SDH) deficient renal cell carcinoma**

**Comment by mingjiecn** [comment]
For real data, if it is cancer, is stage info required in path report? In the test data, some has cancer histology but no stage info. If this is true for real data, then what should we do if stage info is missing? @vsmalladi 

after discussion with @vsmalladi , if there is only one tumor for this patient and the tumor is missing stage info, we can use it as the dominant tumor. Other that that, we will not consider the tumors that are missing stage info.

**Comment by mingjiecn** [comment]
After discussion on 11/5/2020, we will not consider histology that is non-RCC. We will consider benign kidney tumor and they rank at last. For histology in the same group we consider them the same rank. If at the end we have more than on tumors then we use the tumor that has the earliest date.

**Comment by mingjiecn** [comment]
rank | histology from schema
-- | --
6 | collecting duct carcinoma(CDC)
6 | Renal medullary carcinoma
6 | HLRCC
5 | ccRCC
5 | Renal Cell Carcinoma, NOS
5 | Sarcomatoid, NOS
5 | Unclassified
5 | Unclassified RCC
5 | Poorly differentiated malignancy
5 | Soft tissue neoplasm, NOS
4 | PRCC, type 2
4 | MiT family translocation RCC
4 | Tubulocystic RCC
3 | PRCC, no type given
3 | PRCC, type 1
3 | Mucinous tubular and spindle cell carcinoma
3 | Acquired cystic disease-associated RCC
3 | SDH deficient RCC
2 | ChRCC
2 | ChRCC, hybrid type
2 | RON
2 | RON, favor ChRCC
1 | multilocular cystic renal neoplasm of low malignant potential
1 | ccPRCC
0 | Angiomyolipoma
0 | Cystic nephroma
0 | Metanephric adenoma
0 | RO
0 | RON, favor RO
-1 | Leiomyoma
-1 | Leiomyosarcoma
-1 | Sarcoma
-1 | Nephroblastoma (Wilms tumor)

**Comment by vsmalladi** [comment]
@mingjiecn will hold off on merge until histology subtype decisions.

**Comment by mingjiecn** [comment]
On 12/02/2020 update the file, updated the terms and remove the non-RCC types.
[histology subtype spelling confirmed 12022020.xlsx](https://github.com/utsw-bicf/pandiseased/files/5630976/histology.subtype.spelling.confirmed.12022020.xlsx)
