### ISSUE TITLE
Imaging facet filter

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#227]
Add facet to find closest imaging  data within <90 days of a surgery

**Comment by mingjiecn** [comment]
What is the value for this facet? Whether the patient has image data or not within <90 days of the first surgery?  Or  the type of image data within <90 days of every surgery? @vsmalladi

**Comment by mingjiecn** [comment]
After discussion, we will record the type of medical imaging when:

-  happens within 90 days(<90) before any nephrectomy

-  closest to any nephrectomy for a patient for a giving nephrectomy.

**Comment by vsmalladi** [comment]
Close #305
