### ISSUE TITLE
Change search filter for Nephrectomy Robotic Assist

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#259]
Right now it looks like this:
![image](https://user-images.githubusercontent.com/44071821/96178337-deefd200-0ef4-11eb-84f0-3786d6b85b4e.png)

- [x] Change schema: Nephrectomy Robotic Assist is a string instead of boolean

- [x] Change test data to Yes or No.

- [x] Change real data to Yes or No.

**Comment by mingjiecn** [comment]
just realize that calculated field is used for this so no need to change schema, test data and real data. @vsmalladi

**Comment by vsmalladi** [comment]
Nice
