### ISSUE TITLE
Histology: merge unclassified and unclassified RCC. Take out non kidney cancers. Few numbers of pRCC subtypes. 

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#260]
Need to check with Payal or Anala.

**Comment by vsmalladi** [comment]
unclassified RCC

Remove:
Leiomyoma
Leiomyosarcoma
Nephroblastoma (Wilms tumor)
Sarcoma

Make subtype
1. PRCC (Type 1 and Type 2, no type given)
2. CHRCC (classic and eosinophilic)

**Comment by vsmalladi** [comment]
Resolution

Schema Remove:

- [x] unclassified RCC
- [x]  Leiomyoma
- [x] Leiomyosarcoma
- [x] Nephroblastoma (Wilms tumor)
- [x] Sarcoma

Data Remove:

- [x] Change unclassified RCC -> unclassified
- [x]  Leiomyoma
- [x] Leiomyosarcoma
- [x] Nephroblastoma (Wilms tumor)
- [x] Sarcoma

Moving Subtypes to issue #243

**Comment by vsmalladi** [comment]
Data changed
