### ISSUE TITLE
Change search filters for germline mutation

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#263]
- [x] Too few germline cases. So we will take it off for now.
- [x] IHC should go in brackets. For others include sequencing in brackets. for example: change **IHCMLH1** to **MLH1(IHC)** , change **MAX** to **MAX(Sequencing)**. Both schema and test data need to be updated.
- [x] IHC should go in brackets. For others include sequencing in brackets. for example: change **IHCMLH1** to **MLH1(IHC)** , change **MAX** to **MAX(Sequencing)**. real data need to be updated.

**Comment by mingjiecn** [comment]
Don't know what sequences for germline mutations. Assign it to @vsmalladi . If anyone can give some references then you can assign it back to me. Thanks!

**Comment by vsmalladi** [comment]
@mingjiecn can you clarify sequences for germline mutations?

**Comment by vsmalladi** [comment]
@mingjiecn I think it is meant to be 
VHL (Sequencing)

**Comment by mingjiecn** [comment]
@vsmalladi Got it! I can do this!

**Comment by mingjiecn** [comment]
need @vsmalladi to update the real data
