### ISSUE TITLE
Scrub old encode schemas

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#270]
Remove all related to old encode data

- Schemas

**Comment by mingjiecn** [comment]
- [ ] remove encode schemas and python files  in schema folder, audit folder, types folder and upgrade folder
- [ ] remove encode data from test folder
- [ ] remove encode component in components folder 
- [ ] remove encode files from other folder.

The schema we use:

-     'user',
-     'award',
-     'lab',
-     'image',
-     'page',
-     'publication',
-     'document',
-     'patient',
-     'surgery',
-     'pathology_report',
-     'surgery_procedure',
-     'biospecimen',
-     'bioreference',
-     'bioproject',
-     'bioexperiment',
-     'platform',
-     'biolibrary',
-     'bioreplicate',
-     'biofile',
-     'bioexperiment_series',
-     'ihc',
-     'medication',
-     'supportive_medication',
-     'germline',
-     'consent',
-     'radiation',
-     'medical_imaging',
-     'cart',
-     'lab_results',
-     'vital_results'
