### ISSUE TITLE
Paging Through Search Results

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#271]
https://support.smartbear.com/qacomplete/docs/developer/api/rest/api/reference/paging.html
currently we don't have offset, only have limit. Paging can't be done until upgrade.

**Comment by mingjiecn** [comment]
Talked with ENCODE people.
you can use from but that is only activated for report page, e.g.: https://www.encodeproject.org/report/?type=Experiment&from=2&limit=5

The from parameter is ignored on normal search page, e.g.: https://www.encodeproject.org/search/?type=Experiment&from=2&limit=5

For search page you would have to modify how this add_slice function is calculated. You can see only an end value is added: https://github.com/ENCODE-DCC/snovault/blob/0e60fc304962e290fadf6f01b03662468f836ca6/src/snovault/elasticsearch/searches/queries.py#L837

For report page you can see start is also considered in add_slice: 
https://github.com/ENCODE-DCC/snovault/blob/0e60fc304962e290fadf6f01b03662468f836ca6/src/snovault/elasticsearch/searches/queries.py#L922

Encode never used slicing/pagination on search, and there’s some risk of exceeding ES max_result_window by allowing specification of from and limit, but there’s no reason you couldn’t add it if you wanted.

The other thing that complicates it a bit is that we allow limit=all which isn’t a number. And the most efficient (only?) way for ES to return all results is to stream them unordered. So you lose any specified sort in that case. 

Look like there is some risk to use slicing/pagination on search. Need to discuss with @vsmalladi to see if we want to implement it in KCE.

**Comment by mingjiecn** [comment]
after discussion on 17/12/2020, we will do paging on report page. An example will look like this:
![image](https://user-images.githubusercontent.com/44071821/102537728-efe1ce80-4070-11eb-911b-69ca6415e1c1.png)

**Comment by vsmalladi** [comment]
Paging is done on report page. already merged.
