### ISSUE TITLE
Remove pM0

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#280]
Remove pM0 as option

- [x] Change pM0 to Not applicable for schema and test data

- [x] Change pM0 to Not applicable for real data

**Comment by mingjiecn** [comment]
There is also pM0 in old KCE:
![image](https://user-images.githubusercontent.com/44071821/99305910-0dc1d680-281a-11eb-983c-a44d2b471d3d.png)

**Comment by vsmalladi** [comment]
i think we leave this as M0 

M0 (M plus zero): The disease has not metastasized.

M1: The cancer has spread to other parts of the body beyond the kidney area.

https://www.cancer.net/cancer-types/kidney-cancer/stages#:~:text=Common%20areas%20where%20kidney%20cancer,body%20beyond%20the%20kidney%20area.

**Comment by mingjiecn** [comment]
Change pM0 to Not applicable after discuss with Alana and Venkat.

**Comment by mingjiecn** [comment]
Assign @vsmalladi to change the real data.

**Comment by vsmalladi** [comment]
Updated real data
