### ISSUE TITLE
pN2 what to do

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#281]
pN2 to keep or remove

**Comment by mingjiecn** [comment]
pN2 comes from AJCC version 6. There is no pN2 and no AJCC version info for pN in old kce:
![image](https://user-images.githubusercontent.com/44071821/99306149-609b8e00-281a-11eb-93df-133671d36a9e.png)

**Comment by vsmalladi** [comment]
pN2 is on AJCC 6th edition. Actual data.

**Comment by vsmalladi** [comment]
Will keep for now.
