### ISSUE TITLE
Margins status calculated field

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#282]
Margins can be:

1. Postivie
2. Involved
3. Not involved

- [x] Change margins schema to Positive/involved, Not involved, Not available or Not applicable.  

- [x] Change test data to Positive/involved, Not involved, Not available or Not applicable.  

- [x] Change real data to Positive/involved, Not involved, Not available or Not applicable.

**Comment by mingjiecn** [comment]
assign @vsmalladi to fix real data

**Comment by vsmalladi** [comment]
Updated real data
