### ISSUE TITLE
Add tooltip definitions for each filter category

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#285]
Add tool tip definitions for types in each filter categorey. 
![image](https://user-images.githubusercontent.com/44071821/99304328-d4886700-2817-11eb-91c9-d5534e5d214d.png)
It can be done by using description in facet

**Comment by mingjiecn** [comment]
Can we copy the old kce tooltip text?  @vsmalladi

**Comment by vsmalladi** [comment]
Ya we can do that. 

This is all the tooltips

"Age at Diagnosis":"The age of the patient at his or her last birthday before diagnosis of renal tumor. "

"Gender":"Identifies the sex of the patient as recorded in patient\u2019s EMR."

"Ethnicity":"Person of Spanish or Hispanic origin as recorded in patient\u2019s EMR. Patients that declined or their records were not found are not depicted."

"Race":"The primary race of the person (American Indian, Asian, Black, Hawaiian Pacific, White, Others) as recorded in patient\u2019s EMR. Patients that declined or their records were not found are not depicted."

"Vital Status":"Patient's status (Alive or dead) as recorded in EMR or in Tumor Registry (TR)."

"Surgery (at presentation)":"\nThe type (includes radical and nephroureterectomy with RCC) and method (laparoscopic \/ robotic assisted) of nephrectomy and radioablation (of tumor or cyst) for patients that underwent surgery at UTSW. For patients with prior nephrectomy at an outside institution, the type of surgery is recorded as \u201cnot available\u201d. Patients that did not undergo nephrectomy are recorded as \u201cno surgery\u201d (management at UTSW for active surveillance or metastasis without surgical treatment). RCC metastasectomy at UTSW are extracted from pathology reports."

"Imaging Data":" Availability of CT abdomen and pelvis (with or without contrast), MRI abdomen (with or without contrast) and PET done within 90 days prior to surgery. If there are multiple entries of the same imaging modality within 90 days, only the closest to surgery is displayed. "

"Pathology":"For patients with more than one renal tumor, the first RCC was designated as \"primary tumor\" and the data in KCE is in reference to this tumor. If you would like to query all the tumors for each patient, please select variables from the tab \"Secondary Tumors\"",

"Secondary Tumors":"Secondary tumors with higher stage than the primary tumor for a given patient.",

"Laterality":"Laterality of the tumor is recorded when available in the pathology report.",

"Size":"Greatest dimension of tumor was recorded in cm.",

"Focality":"Single or multiple foci of tumors in that specimen is recorded when available. ",

"Sarcomatoid":"Presence of sarcomatoid dedifferentiation when reported",

"Necrosis":"Presence of tumor necrosis (this is available only after 2012).",

"Grade":" Highest Fuhrman or ISUP grade seen in tumor, 1-4. Benign tumors and ChRCC are recorded as \u201cnot applicable\u201d. Tumors for which grade was not reported in pathology are considered \u201cnot available\u201d. Some of the cases have been reviewed centrally, and the centrally reviewed grade has been depicted in KCE for these cases. ",

"Margin Status":" Tumor transected at the surgical margins are considered positive.",

"LVI":"Lymphovascular invasion in non-muscle containing vessels.",

"Perinephric Infiltration":"Tumor extension into perinephric tissues, confirmed by microscopy.",

"Renal Vein Involvement":"Tumor extension into major renal veins, confirmed by microscopy.",

"Ipsilateral Adrenal Gland Involvement":" Tumor extension into adrenal gland, contiguous or not (this was reported only after 2010 and were derived based on gross description in prior pathology reports. If not stated in old reports, it was assumed to be continuous). "

,"Pelvicaliceal involvement":"Tumor extension into pelvicalyceal (this will be part of staging 2018 onwards and is may not be mentioned in the prior pathology reports). ","

"TNM Stage 6th":"Composite stage based on 6th edition rules.","
TNM Stage 7th":"Composite stage based on 7th edition rules. ","

Metastasis, NOS":"The time of metastasis in reference to time of diagnosis is currently unknown for these cases. As the TR data is updated, these data will be available in KCE",

"Metastatic Site":"This is recorded either from pathology report using natural language search or from clinical and radiotherapy notes. These may not be all inclusive.",

"Histology Proven":"Record of metastatic RCC in pathology reports and nephrectomy specimens are considered histologically proven. ",

"Drug":"The duration (in days) of the following prescribed Cancer and Support drugs (courtesy Dr. Bowman) are recorded and sequentially considered as line of therapy. ",

"Radiation Therapy":"Patients with RCC that received radiotherapy (any technique including SBRT and Stereotactic radiotherapy) at UTSW. The date, dose, fraction, and site of RT are extracted. The patient may receive RT to multiple sites. Brain RT data were partly manually extracted. ",

Histology done in #299 
"ACD-RCC":"Acquired cystic disease-associated RCC",
"ccPRCC":"Clear cell papillary renal cell carcinoma",
"ccRCC":"Clear cell renal cell carcinoma ",
"ChRCC":"Chromophobe renal cell carcinoma, classic and eosinophilic type",
"CDC":"Collecting duct Carcinoma",
"HLRCC":"Hereditary leiomyomatosis and RCC-associated RCC",
"MTSCC":"Mucinous tubular and spindle cell carcinoma",
"MCRCC":"Multilocular cystic renal neoplasm of low malignant potential",
"PRCC":"Papillary renal cell carcinoma",
"RM":"Renal medullary carcinoma",
"Sarcoma":"Sarcoma, NOS",
"tRCC":"MiT family translocation RCC",
"TC":"Tubulocystic RCC",
"RCC, NOS":"RCC, Unknown subtype"
,"RCC, UC":"RCC, Unclassified",
"RO":"RO:Oncocytoma (includes renal oncocytic neoplasm)"
,"CN":"Cystic nephroma."
,"MA":"Metanephric adenoma.",
"AML":"Angiomyolipoma.",
