### ISSUE TITLE
Remove UTSWCoPath from Surgery Site

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#286]
- [x] Remove UTSW CoPath from Surgery Site for test data
- [x] Remove UTSW CoPath from Surgery Site for real data

**Comment by vsmalladi** [comment]
Reset UTSW CoPath -> UTSW Hositpal for cases that didn't have nephrectemies

**Comment by mingjiecn** [comment]
assign @vsmalladi  to fix real data

**Comment by vsmalladi** [comment]
Real data fixed
