### ISSUE TITLE
Check histology subtype spelling

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#288]

**Comment by vsmalladi** [comment]
Current histologies need to go over what they should be. Linked to #260 #243 

- [x] Acquired cystic disease-associated RCC
- [x] Angiomyolipoma
- [x] ccPRCC
- [x] ccRCC
- [x] ChRCC
- [x] ChRCC, hybrid type
- [x] collecting duct carcinoma(CDC)
- [x] Cystic nephroma
- [x] HLRCC
- [x] Metanephric adenoma
- [x] Mucinous tubular and spindle cell carcinoma
- [x] multilocular cystic renal neoplasm of low malignant potential
- [x] PRCC, no type given
- [x] PRCC, type 1
- [x] PRCC, type 2
- [x] Poorly differentiated malignancy
- [x] Renal medullary carcinoma
- [x] Renal Cell Carcinoma, NOS
- [x] RO
- [x] RON
- [x] RON, favor ChRCC
- [x] RON, favor RO
- [x] Sarcomatoid, NOS
- [x] MiT family translocation RCC
- [x] Tubulocystic RCC
- [x] Unclassified RCC
- [x] Soft tissue neoplasm, NOS
- [x] SDH deficient RCC

**Comment by mingjiecn** [comment]
[histology subtype spelling.xlsx](https://github.com/utsw-bicf/pandiseased/files/5567488/histology.subtype.spelling.xlsx)



Subtype(new   kce) | short name(old kce) | Subtype(old kce) | remove? | Updated subtype for new kce
-- | -- | -- | -- | --
RO | RO | RO:Oncocytoma (includes renal   oncocytic neoplasm) | no | ?
RON,   favor RO |   |   | no | ?
ChRCC,   hybrid type |   |   | no | ?
RON |   |   | no | ?
RON,   favor ChRCC |   |   | no | ?
SDH   deficient RCC |   |   | no | ?
Poorly   differentiated malignancy |   |   | no | ?
Sarcomatoid,   NOS |   |   | no | ?
Soft   tissue neoplasm, NOS |   |   | no | ?
Unclassified |   |   | no | ?
PRCC, no   type given | PRCC | Papillary renal cell carcinoma | no | Papillary renal cell   carcinoma(PRCC)
Acquired   cystic disease-associated RCC | ACD-RCC | Acquired cystic   disease-associated RCC | no | Acquired cystic   disease-associated RCC(ACD-RCC)
Angiomyolipoma | AML | Angiomyolipoma | no | Angiomyolipoma(AML)
ChRCC | ChRCC | Chromophobe renal cell   carcinoma, classic and eosinophilic type | no | Chromophobe renal cell   carcinoma, classic and eosinophilic type(ChRCC)
ccPRCC | ccPRCC | Clear cell papillary renal cell   carcinoma | no | Clear cell papillary renal cell   carcinoma(ccPRCC)
ccRCC | ccRCC | Clear cell renal cell   carcinoma | no | Clear cell renal cell carcinoma   (ccRCC)
collecting   duct carcinoma(CDC) | CDC | Collecting duct Carcinoma | no | Collecting duct Carcinoma(CDC)
Cystic   nephroma | CN | Cystic nephroma | no | Cystic nephroma(CN)
HLRCC | HLRCC | Hereditary leiomyomatosis and   RCC-associated RCC | no | Hereditary leiomyomatosis and   RCC-associated RCC(HLRCC)
Metanephric   adenoma | MA | Metanephric adenoma. | no | Metanephric adenoma.(MA)
MiT   family translocation RCC | tRCC | MiT family translocation RCC | no | MiT family translocation   RCC(tRCC)
Mucinous   tubular and spindle cell carcinoma | MTSCC | Mucinous tubular and spindle   cell carcinoma | no | Mucinous tubular and spindle   cell carcinoma(MTSCC)
multilocular   cystic renal neoplasm of low malignant potential | MCRCC | Multilocular cystic renal   neoplasm of low malignant potential | no | Multilocular cystic renal   neoplasm of low malignant potential(MCRCC)
PRCC,   type 1 |   |   | no | Papillary renal cell   carcinoma(PRCC, type 1)
PRCC,   type 2 |   |   | no | Papillary renal cell   carcinoma(PRCC, type 1)
Unclassified   RCC | RCC, UC | RCC, Unclassified | yes | RCC, Unclassified(RCC, UC)
Renal   Cell Carcinoma, NOS | RCC, NOS | RCC, Unknown subtype | no | RCC, Unknown subtype(RCC, NOS)
Renal   medullary carcinoma | RM | Renal medullary carcinoma | no | Renal medullary carcinoma(RM)
Tubulocystic   RCC | TC | Tubulocystic RCC | no | Tubulocystic RCC(TC)
Leiomyoma |   |   | yes |  
Leiomyosarcoma |   |   | yes |  
Nephroblastoma   (Wilms tumor)", |   |   | yes |  
Sarcoma | Sarcoma | Sarcoma, NOS | yes |

**Comment by mingjiecn** [comment]
#221 need to be reopened if there is any spelling change.

**Comment by mingjiecn** [comment]
[histology subtype spelling confirmed.xlsx](https://github.com/utsw-bicf/pandiseased/files/5624073/histology.subtype.spelling.confirmed.xlsx)

**Comment by mingjiecn** [comment]
On 12/02/2020 update the file, add one possible missing type for real data and add ranking.
[histology subtype spelling confirmed 12022020.xlsx](https://github.com/utsw-bicf/pandiseased/files/5630976/histology.subtype.spelling.confirmed.12022020.xlsx)

**Comment by vsmalladi** [comment]
All real data updated.
