### ISSUE TITLE
Update facet terms sorting

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#291]
Currently the default sorting for facet terms is to sort the terms by the number of records in descending order. We already develop a new way of sorting, if you add range in the facet name then it will sort the term by numeric values stored in the term's text field. There are several other way of sorting will be nice to have:

- [x] Sort the terms alphabetically, this can be useful for facet Histologic Subtype

- [x] Sort the terms  by numeric value stored in the term's text field if there is numeric value, if no numeric value, them those terms are at the bottom and sort alphabetically. This can be useful for facet like “Grade” - 1, 2, 3, 4 NA, NP
- [x] More complicated sorting for facet for Path Stage - 1,1a,1b, 2, 2a, 2b… 

The following facet filters need to be sorted:
Sort alphabetically:

- [x] dominant_tumor.histology_filter
- [x] surgery.pathology_report.histology_filter
- [x] pathology_report.histology_filter

Sorting for path stage:

- [x] surgery.pathology_report.t_stage
- [x] surgery.pathology_report.n_stage
- [x] surgery.pathology_report.m_stage
- [x] surgery.pathology_report.ajcc_tnm_stage
- [x] pathology_report.t_stage
- [x] pathology_report.n_stage
- [x] pathology_report.m_stage
- [x] pathology_report.ajcc_tnm_stage

Sort by numerical value:

- [x] diagnosis.age_range
- [x] diagnosis.follow_up_duration_range
- [x] surgery.pathology_report.pathology_report_tumor_range
- [x] medication_range
- [x] radiation.dose_range
- [x] radiation.fractions_range
- [x] pathology_report.pathology_report_tumor_range
- [x] pathology_report.grade
- [x] surgery.pathology_report.ajcc_version
- [x] pathology_report.ajcc_version

**Comment by vsmalladi** [comment]
Duplicates #277
