### ISSUE TITLE
Rearrange path report search facets

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#294]
For both surgery view and path report view
- [x] move Status to the end

- [x] move "Histologic Subtype" under "Tumor Size Range"

- [x] move "Grade" under "Histologic Subtype"

- [x] AJCC Version needs to go prior to AJCC TNM Stage

**Comment by vsmalladi** [comment]
@mingjiecn can we also do these changes on surgery view?
