### ISSUE TITLE
Pie chart and bar diagram at the top of search view page

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#295]
Pie chart and bar diagram at the top of search view page, and those charts will change based on the filters selected. We can do similar with old kce:
![image](https://user-images.githubusercontent.com/44071821/99313091-96de0b00-2824-11eb-8a74-5402452f3c7a.png)

![image](https://user-images.githubusercontent.com/44071821/99313136-a8271780-2824-11eb-9719-84e3793bacb0.png)

**Comment by vsmalladi** [comment]
duplicated by #147
