### ISSUE TITLE
Line up list view

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#331]
![image](https://user-images.githubusercontent.com/1130240/102795148-068a6d00-4372-11eb-9170-479678825f10.png)

**Comment by mingjiecn** [comment]
- [x] Line up patient list view
- [x] Line up biospecimen list view
- [x] Line up surgery list view
- [x] Line up dataset list view
- [x] Line up path report list view
- [x] Line up experiment list view

![image](https://user-images.githubusercontent.com/44071821/103023659-0033f680-4514-11eb-98c4-d9abbc23cf56.png)
