### ISSUE TITLE
link between surgery procedure and path report

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#333]
Right now the data is linked this way: The surgery procedures are linked to the surgery and the path reports are linked to the surgery too. But there is no direct link between surgery procedure and path report.
If some time surgery procedure info is missing but we have path report info for this surgery, is it possible that we create a procedure type which is "Not available", then we can still have this link surgery -> surgery procedure -> path report

**Comment by vsmalladi** [comment]
Yes will update mmodel to make this better. will stil create some empty items but will link better. 

surgery -> surgery procedure -> path report

Will start updating the code.
