### ISSUE TITLE
Typo "Metasis" in javascript file and json file

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#334]
Typo "Metasis" in javascript file and json file
source type should be path_metastasis
site should be Metastatic Site 
type Metastatic Type
![image](https://user-images.githubusercontent.com/44071821/102800185-21141480-4379-11eb-9fc6-360d5ba2699b.png)

**Comment by mingjiecn** [comment]
Assign @vsmalladi to fix real data path_source_procedure in path report

**Comment by vsmalladi** [comment]
@mingjiecn can you but merge request in for this branch and I can then fix and merge

**Comment by vsmalladi** [comment]
Real data updated.
