### ISSUE TITLE
Surgery view will not show path report info until you refresh it

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#339]
Before refresh:
![image](https://user-images.githubusercontent.com/44071821/103238840-8c2d9000-4911-11eb-9b04-59365dfbe591.png)
after refresh:
![image](https://user-images.githubusercontent.com/44071821/103238863-9a7bac00-4911-11eb-95b3-71bef88ca926.png)

**Comment by vsmalladi** [comment]
Potential indexing issue

**Comment by mingjiecn** [comment]
> Potential indexing issue

No it is not. The data was processed after the first rendering. That is why there is no data shown after first rendering. I already fixed it.

**Comment by vsmalladi** [comment]
Okay cool. Great.
