### ISSUE TITLE
Add/update tooltips and definitions

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#341]

**Comment by SenseCode** [comment]
**These are the tooltips currently we have:**

    "ACD-RCC": "Acquired cystic disease-associated renal cell carcinoma",
    "AML": "Angiomyolipoma",
    "ChRCC": "Chromophobe renal cell carcinoma",
    "ccPRCC": "Clear cell papillary renal cell carcinoma",
    "ccRCC": "Clear cell renal cell carcinoma",
    "CDC": "Collecting duct carcinoma",
    "CN": "Cystic nephroma",
    "FH RCC": "Hereditary leiomyomatosis and RCC-associated RCC",
    "MA": "Metanephric adenoma",
    "MiT TRCC": "MiT family translocation renal cell carcinoma",
    "MTSCC": "Mucinous tubular and spindle cell carcinoma",
    "MCRN": "Multilocular cystic renal neoplasm of low malignant potential",
    "RON": "Oncocytic renal neoplasm, not further classified",
    "RO": "Oncocytoma",
    "Other": "Other",
    "PRCC": "Papillary renal cell carcinoma",
    "RCC, NOS": "Renal cell carcinoma, not further classified",
    "RMC": "Renal medullary carcinoma",
    "SDH RCC": "SDH deficient renal cell carcinoma",
    "TC RCC": "Tubulocystic renal cell carcinoma",
    "Unclassified RCC": "Unclassified RCC",
    "Age at Diagnosis": "The age of the patient at his or her last birthday before diagnosis of renal tumor.",
    "Sex": "Identifies the sex of the patient as recorded in patient's EMR.",
    "Ethnicity": "Person of Spanish or Hispanic origin as recorded in patient's EMR. Patients that declined or their records were not found are recorded as unknown.",
    "Race": "The primary race of the person (American Indian, Asian, Black, Hawaiian Pacific, White, Others) as recorded in patient's EMR.",
    "Vital Status": "Patient's status (Alive or Deceased) as recorded in EMR or in Tumor Registry (TR).",
    "Medical Imaging": " Types of medical imaging (CT abdomen and pelvis (with or without contrast), MRI abdomen (with or without contrast) and PET done within 90 days prior to Nephrectomy . If there are multiple entries of the same imaging modality within 90 days, only the closest to Nephrectomyis displayed.",
    "Tumor Laterality":"Laterality of the tumor is recorded when available in the pathology report.",
    "Tumor Size Range":"Greatest dimension range of tumor was recorded in cm.",
    "Tumor Focality":"Single or multiple foci of tumors in that specimen is recorded when available.",
    "Sarcomatoid Change":"Presence of sarcomatoid dedifferentiation when reported",
    "Tumor Necrosis":"Presence of tumor necrosis (this is available only after 2012).",
    "Tumor Grade":" Highest Fuhrman or ISUP grade seen in tumor, 1-4. Benign tumors and ChRCC are recorded as not applicable. Tumors for which grade was not reported in pathology are considered not available. Some of the cases have been reviewed centrally, and the centrally reviewed grade has been depicted in KCE for these cases.",
    "Margin Status":" Tumor transected at the surgical margins are considered positive/involved.",
    "Lymphvascular invasion(LVI)":"Lymphovascular invasion in non-muscle containing vessels.",
    "Perinephric Infiltration":"Tumor extension into perinephric tissues, confirmed by microscopy.",
    "Renal Vein Involvement":"Tumor extension into major renal veins, confirmed by microscopy.",
    "Ipsilateral Adrenal Gland Involvement":" Tumor extension into adrenal gland, contiguous or not (this was reported only after 2010 and were derived based on gross description in prior pathology reports. If not stated in old reports, it was assumed to be continuous).",
    "Pelvicaliceal involvement":"Tumor extension into pelvicalyceal (this will be part of staging 2018 onwards and is may not be mentioned in the prior pathology reports).",
    "TNM Stage 6th":"Composite stage based on 6th edition rules.",
    "TNM Stage 7th":"Composite stage based on 7th edition rules.",
    "Metastatic Site":"This is recorded either from pathology report using natural language search or from clinical and radiotherapy notes. These may not be all inclusive.",
    "Metastasis Histology Proven":"Record of metastatic RCC in pathology reports and nephrectomy specimens are considered histologically proven.",
    "Medication Duration":"The duration (in months) of the following prescribed Cancer and Support drugs (courtesy Dr. Bowman) are recorded.",
    "Radiation Treatment Status":"Patients with RCC that received radiotherapy (any technique including SBRT and Stereotactic radiotherapy) at UTSW. The date, dose, fraction, and site of RT are extracted. The patient may receive RT to multiple sites. Brain RT data were partly manually extracted."
  These are the missing tooltips from the old KCE:

        "Gender": "Identifies the sex of the patient as recorded in patient’s EMR.",
        "Biometrics and Blood Work": "Biometric parameters (Blood Pressure (BP) and Body Mass Index (BMI)) and laboratory values (serum albumin, creatinine, corrected calcium, hemoglobin, lactate dehydrogenase (LDH), neutrophils, platelets, sodium and WBC count) recorded in the patient's EMR within 30 days prior to surgery or start of cancer drugs. If there are multiple entries of the same parameter within 30 days, the closest to surgery or start of cancer drug are displayed. ",
        "Surgery (at presentation)": "The type (includes radical and nephroureterectomy with RCC) and method (laparoscopic / robotic assisted) of nephrectomy and radioablation (of tumor or cyst) for patients that underwent surgery at UTSW. For patients with prior nephrectomy at an outside institution, the type of surgery is recorded as “not available”. Patients that did not undergo nephrectomy are recorded as “no surgery” (management at UTSW for active surveillance or metastasis without surgical treatment). RCC metastasectomy at UTSW are extracted from pathology reports.",
        "Imaging Data": " Availability of CT abdomen and pelvis (with or without contrast), MRI abdomen (with or without contrast) and PET done within 90 days prior to surgery. If there are multiple entries of the same imaging modality within 90 days, only the closest to surgery is displayed. ",
        "Pathology": "For patients with more than one renal tumor, the first RCC was designated as \"primary tumor\" and the data in KCE is in reference to this tumor. If you would like to query all the tumors for each patient, please select variables from the tab \"Secondary Tumors\"",
        "Secondary Tumors": "Secondary tumors with higher stage than the primary tumor for a given patient.",
        "Laterality": "Laterality of the tumor is recorded when available in the pathology report.",
        "Size": "Greatest dimension of tumor was recorded in cm.",
        "Focality": "Single or multiple foci of tumors in that specimen is recorded when available. ",
        "Sarcomatoid": "Presence of sarcomatoid dedifferentiation when reported",
        "Necrosis": "Presence of tumor necrosis (this is available only after 2012).",
        "Grade": " Highest Fuhrman or ISUP grade seen in tumor, 1-4. Benign tumors and ChRCC are recorded as “not applicable”. Tumors for which grade was not reported in pathology are considered “not available”. Some of the cases have been reviewed centrally, and the centrally reviewed grade has been depicted in KCE for these cases. ",
        "LVI": "Lymphovascular invasion in non-muscle containing vessels.",
        "3A": "Highest substage between path and clinical stage (TR) for pT3 and 4. ",
        "3B": "Highest substage between path and clinical stage (TR) for pT3 and 4. ",
        "3C": "Highest substage between path and clinical stage (TR) for pT3 and 4. ",
        "PN": "highest substage between path and clinical stage (TR).",
        "Metastasis, NOS": "The time of metastasis in reference to time of diagnosis is currently unknown for these cases. As the TR data is updated, these data will be available in KCE",
        "Histology Proven": "Record of metastatic RCC in pathology reports and nephrectomy specimens are considered histologically proven. ",
        "Drug": "The duration (in days) of the following prescribed Cancer and Support drugs (courtesy Dr. Bowman) are recorded and sequentially considered as line of therapy. ",
        "Radiation Therapy": "Patients with RCC that received radiotherapy (any technique including SBRT and Stereotactic radiotherapy) at UTSW. The date, doze, fraction, and site of RT are extracted. The patient may receive RT to multiple sites. Brain RT data were partly manually extracted. ",
        "HLRCC": "Hereditary leiomyomatosis and RCC-associated RCC",
        "MCRCC": "Multilocular cystic renal neoplasm of low malignant potential",
        "RM": "Renal medullary carcinoma",
        "Sarcoma": "Sarcoma, NOS",
        "tRCC": "MiT family translocation RCC",
        "TC": "Tubulocystic RCC",
        "RCC, UC": "RCC, Unclassified",
        "Biometrics and Labs": "Values at different time points during the course of the disease",
        "Nephrectomy": "Within 30 days prior to date of nephrectomy.",
        "First line Therapy": "Within 30 days prior to date of treatment.",
        "Second line Therapy": "Within 30 days prior to date of treatment.",
        "Third line Therapy": "Within 30 days prior to date of treatment.",
        "Fourth line Therapy": "Within 30 days prior to date of treatment.",

I will update a list with what we need for extra facets here and ask them what they want to put.

**Comment by vsmalladi** [comment]
Definitions page updates

Patient Demographics

- [ ] Accession (KCEPTXXXXXX): A unique identifier for each patient, treated for renal tumor at UT Southwestern between 1998-current. This number protects the identity of the patient. If the patient information is deleted from KCE, the ID is not reused. 

- [ ] Sex: Identifies the sex of the patient as recorded in the patient’s EMR.

- [ ]  Ethnicity: Persons of Spanish or Hispanic origin as recorded in the patient’s EMR. 

- [ ] Race: The primary race of the person (American Indian, Asian, Black, Hawaiian Pacific, White, Others) as recorded in the patient’s EMR. 

- [ ] Age at Diagnosis: The age of the patient in years at diagnosis of renal tumor.

- [ ] Last Follow Up Date: Patient's most recent visit date as recorded in EMR.

- [ ] Vital Status: Patient's status (Alive or deceased) as recorded in EMR or in Tumor Registry.

- [ ] Dominant tumor: The patient's dominant tumor based on current data availability ( stage, histology and size)

Surgery

- [ ] Accession (KCESXXXXXXX): A unique identifier for each surgery. 
- [ ] Hospital Location: The location procedure was conducted For patients with surgery at an outside institution, the surgery hospital location is recorded as “Outside”.
- [ ] Surgery Treatment Summary: The surgery treatment status. For patients that did not undergo surgery,  their status is recorded as “No” (management at UTSW for active surveillance or metastasis without surgical treatment).
- [ ] Procedure: The surgical procedure conducted as recorded in the EMR. 
- [ ] Nephrectomy details: The Nephrectomy type, and the method (Nephrectomy approach and nephrectomy robotic assist) of nephrectomy for patients that underwent surgery. 

Pathology Report

- [ ] Accession (KCEPRXXXXXX): A unique identifier for each pathology report to anonymize patient data.

- [ ] Laterality: Laterality of the tumor is recorded when available in the pathology report. 

- [ ] Size: The greatest dimension of the tumor was recorded in cm. 
- [ ] Focality: Single or multiple foci of tumors in that specimen is recorded when available.
- [ ] Sarcomatoid: The presence of sarcomatoid dedifferentiation when reported. The percentage is reported if available.

- [ ] Necrosis: The presence of tumor necrosis (this is available only after 2012).

- [ ] Grade: highest Fuhrman or ISUP grade seen in tumor, 1-4. ChRCC are recorded as “Not applicable”. Tumors for which grade was not reported in pathology are considered “Not available”.

- [ ] Margins: Tumor transected at the surgical margins are considered positive.

- [ ] LVI: Lymphovascular invasion in non-muscle containing vessels.

- [ ] Perinephric Infiltration: Tumor extension into perinephric tissues, identified microscopically.

- [ ] Renal Vein Involvement: Tumor extension into major renal veins, identified microscopically.

- [ ] Ipsilateral Adrenal Gland Involvement: Tumor extension into adrenal gland, identified microscopically. Contiguous or not (this was reported only after 2010 and were derived based on gross description in prior pathology reports. If not stated in old reports, it was assumed to be continuous).

- [ ] Pelvicaliceal Involvement: Tumor extension into pelvicalyceal, identified microscopically (this will be part of staging 2018 onwards and is may not be mentioned in the prior pathology reports).

- [ ] AJCC TNM stage: Included both the pathology and clinical stage. The edition used is noted at the time of report.
- [ ] Remove all text below "AJCC TNM stage"


- [ ] Metastasis: Remove
- [ ] Medication: Remove


Follow up Data 

- [ ] Change title to Dates

- [ ] Please note that all dates displayed are not true dates and are displayed as a reference to express the timeframe of events and anonymize patients.

- [ ]  Diagnosis Date: The earliest date of diagnosis of renal tumor (irrespective of the laterality and focality). It is the earliest date of any of the following: documented renal carcinoma in patient’s electronic medical records (EMR) in clinical notes, or date of nephrectomy or date of metastasis or initiation of treatment for (medication or radiation). If physicians stated that in retrospect the patient had cancer earlier, earlier date is used. Ambiguous terms in the notes are not used for diagnosis (likely, cannot be ruled out, suggests, worrisome, possible, potentially malignant). When treatment is received as first course before definite diagnosis, treatment date was used as date of diagnosis. For nephrectomies with benign tumors, date of nephrectomy as considered date of diagnosis. Date of diagnosis/resection of contralateral tumor in an outside institution is not always available but when available was considered as date of diagnosis. When only the year is available, the 1st of July for that year, if only month is available, 1st of that month is considered as date of diagnosis.

- [ ] Surgery Date: The date (yyyy-mm-dd) of nephrectomy, RCC metastasectomy, biopsy and/or radioablation are recorded for patients that underwent surgery at UTSW . Data are extracted from CPT codes and when not available from pathology reports. For patients with prior nephrectomy at an outside institution, the data are extracted whenever available from pathology reports. If only the month and year are available, the date was rounded to 01 for that month. If only the year is available, the date is rounded to July first of that year. If no dates were available, it is recorded as “not available”.

Other:

- [ ] Radiation Treatment: Patients with RCC that received radiotherapy (any technique including SBRT and Stereotactic radiotherapy) at UTSW. The date, dose, fraction, and site of RT are extracted. The patient may receive RT to multiple sites. Brain RT data were partly manually extracted.
- [ ] Medication: The duration (in days) of the prescribed cancer drugs as recorded in EMR.
- [ ] Supportive medication: The duration (in days) of the prescribed supportive drugs as recorded in EMR.

Summary definitions :

- [ ] Metastasis Status: Patients that had histologic proven metastasis either at the time of nephrectomy or subsequently (FNA, core biopsy or metastasectomy), or patients started on systemic cancer drug, or received radiotherapy in non-renal site (including thrombus) or stated to have metastasis in the clinical notes are categorized as “Yes”.
- [ ] Metastasis Site: This is recorded either from pathology report using natural language search or from clinical and radiotherapy notes. These may not be all-inclusive.
- [ ] Histology Proven: Record of metastatic RCC in pathology reports and nephrectomy specimens are considered histologically proven.

- [ ]  Biometric Parameters and Basic Blood Workup (Facets): Biometric parameters (Blood Pressure (BP_Systolic and BP_Diastolic) and Body Mass Index (BMI)) and laboratory values (serum albumin, creatinine, corrected calcium, hemoglobin, lactate dehydrogenase (LDH), neutrophils, platelets, sodium and WBC count) recorded in the patient's EMR within 30 days prior to first nephrectomy. If there are multiple entries of the same parameter within 30 days, the closest to surgery are displayed.

- [ ]  Medical Imaging (Facets): Types of medical imaging (CT abdomen and pelvis (with or without contrast), MRI abdomen (with or without contrast), and PET done within 90 days prior to Nephrectomy. If there are multiple entries of the same imaging modality within 90 days, only the closest to Nephrectomy is displayed.

- [ ] Germline Mutation (Table): Mutation of clinical significance or a variant of uncertain clinical significance in any of the genes from 76 cancer genes tested at the UTSW Genetics lab for these patients when available.

**Comment by SenseCode** [comment]
Need to add these for tooltips.

![image](https://user-images.githubusercontent.com/38848214/103711417-00ed7380-4f7d-11eb-93e5-4e1947aff613.png)
![image](https://user-images.githubusercontent.com/38848214/103711450-12368000-4f7d-11eb-956c-c8e72a4cf467.png)
![image](https://user-images.githubusercontent.com/38848214/103711730-a3a5f200-4f7d-11eb-85c5-0d08513715ed.png)
