### ISSUE TITLE
Consolidate Radiation Site

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#347]
Consolidate Radiation Site
"enum": [
                    "Adrenal",
                    "Bone",
                    "Brain",
                    "Liver",
                    "Lung",
                    "Lymph node",
                    "Other",
                    "Kidney"
                ],

For the radiation treatment chart, this is what it looks right now:
![image](https://user-images.githubusercontent.com/44071821/103935323-061d0080-50ec-11eb-9173-72873176d3a6.png)

We should used consolidated site for y axis label, and use site_general in the tooltip so the charts will look unified.

**Comment by vsmalladi** [comment]
I agree. Lets do that.
