### ISSUE TITLE
Is there direct link between parent and children sample in OpenSpecimen

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#351]
From the Openspecimen data, there is a field called called Specimen_Lineage to tell you whether a sample is parent or derived sample, but there is not direct link to tell the child sample links to which parent sample. 

If there is not direct link from Openspecimen than we can't tell which children is link to which parent and we need to remove the property originated_from in Biospecimen.

**Comment by alanachristie** [comment]
There is a field in OS for the name of the parent sample, so we will be able to keep this property. I will make sure to output and update.

**Comment by mingjiecn** [comment]
Sure. We will update the data in kce once you have this part of data.

**Comment by vsmalladi** [comment]
Perfect confirmmed fields to use. Updating data
