### ISSUE TITLE
Do we collect metastatic tissue?

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#354]
From data in OpenSpecimen Specimen_Pathological Status, looks like we only collect those type of tissue: Malignant, Non-Malignant and Not specified.  In the definition of Specimen_Pathological Status, I saw there is option for Metastatic. Do we collect metastatic tissue?

**Comment by alanachristie** [comment]
We do collect metastatic tissue, but Dr. B did not want the XP team to mark this in OS, so these are also marked with "Malignant".

**Comment by mingjiecn** [comment]
OK, we will need 

- give a definition for specimen pathological status so the user will understand how to find metastatic tissue. Will set up an issue for all specimen related tooltip.
- remove test data for metastatic type in this issue.

Thank you @alanachristie !
