### ISSUE TITLE
Do we still need to link one biospecimen wth surgery when path number is not provided in openspecimen?

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#355]
There are samples(Tissue, Fluid and Cell) in openspecimen has not path number info. Do we still need to link them with surgery. We can link them using patient surgery date in KCE and visit date in Openspecimen.

**Comment by alanachristie** [comment]
I think if there is no path number, but there is a matching date, then yes, we can link the biospecimen with the surgery. Not all of these biospecimens will have a match to a patient surgery date though: there are definitely blood collections that won't match up to any surgeries, as well as patients who had surgeries at Parkland that we don't have the surgery data for (yet).

**Comment by mingjiecn** [comment]
@vsmalladi we will see if we can link biospecimen with surgery by patient and visit date. Non surgical sample can be also linked to a surgery if we define a time frame. It will be useful for blood sample so we can still have case diagnosis for those samples. We can discuss it later if blood sample diagnosis is needed. This can be closed now.
