### ISSUE TITLE
Biospecimen primary site

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/pandiseased#357]
Do we have primary site info in Openspecimen? Do we need primary site info?
I assume that for all the samples the primary site will be Kidney. Right now in Biospecimen schema, the default primary site is kidney.

**Comment by alanachristie** [comment]
We do not have really have primary site info. The closest is the clinical diagnosis on the visit form, where we could put "renal cell carcinoma" to indicate the primary site, but we don't put anything here currently. I think Christina has been talking with Rebecca to have this as the default though?
In any case, there are some rare cases of primaries from sites other than the kidney, so while kidney is definitely the default primary, it doesn't necessarily apply to all.

**Comment by mingjiecn** [comment]
since we will not have any data for primary site currenttly, I will remove the default value for now so there will be no data for primary site. Thank you @alanachristie !
