### ISSUE TITLE
Should we explain the tumor stage in tooltips and document

### ISSUE THREAD

**Issue by SenseCode** [utsw-bicf/pandiseased#371]
![image](https://user-images.githubusercontent.com/38848214/104383196-11f63180-54f5-11eb-972a-e0c3e1eab144.png)
![image](https://user-images.githubusercontent.com/38848214/104383209-1884a900-54f5-11eb-8cf4-7c0c751c9e5d.png)
![image](https://user-images.githubusercontent.com/38848214/104383219-1c183000-54f5-11eb-931a-8919157654a5.png)
![image](https://user-images.githubusercontent.com/38848214/104383247-24706b00-54f5-11eb-9b4c-d8a03e77e59d.png)

**Comment by vsmalladi** [comment]
Ya i think we should
