### ISSUE TITLE
Update help pop up

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#372]

**Comment by mingjiecn** [comment]
I can't find related code.

**Comment by mingjiecn** [comment]
help pop up menu is generated by outside script. We can remove it.

_<script async src={`https://cdn.walkme.com/users/8c7ff9322d01408798869806f9f5a132/${globals.isProductionHost(this.props.href) ? '' : 'test/'}walkme_8c7ff9322d01408798869806f9f5a132_https.js`} />_
