### ISSUE TITLE
Set visualization rules on consent

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#391]
Set visualization at multiple levels (Status) based on consent inforamtion

**Comment by vsmalladi** [comment]
1. Check schema
2. Improt of data
3. Discuss implciation on filtering and access

**Comment by SenseCode** [comment]
- [x] rules:
![image](https://user-images.githubusercontent.com/38848214/113321894-acd30080-92d9-11eb-909c-72763bec0148.png)

- [x] remove unknown data
- [x] remove HIPPA
- [x] Change version with timeline order: which means switch ver5 and ver6, currently only 1 ver6 data.
- [ ] Filter genomic:
![image](https://user-images.githubusercontent.com/38848214/113322894-e0faf100-92da-11eb-82e9-6ec4083272b3.png)

- [ ] patient page have germline and biospecimen, should we set filter according to consent?

- [x] status change from shared status to normal status? (Which includes revoke...)

**Comment by vsmalladi** [comment]
Create caluclated field for genomic release.

**Comment by SenseCode** [comment]
![image](https://user-images.githubusercontent.com/38848214/113352911-870e2180-9302-11eb-808a-28910207dffa.png)
![image](https://user-images.githubusercontent.com/38848214/113352941-93927a00-9302-11eb-9f0a-b38ee584492b.png)

**Comment by vsmalladi** [comment]
Should control view based on status.js

**Comment by vsmalladi** [comment]
WE can set external vs consortium vs administrator access status
for each type of object

**Comment by vsmalladi** [comment]
Example
```
    File: {
        external: [
            'released',
            'archived',
            'revoked',
        ],
        unprivileged: [
        ],
        consortium: [
            'in progress',
            'uploading',
            'upload failed',
            'content error',
        ],
        administrator: [
            'deleted',
            'replaced',
        ],
    },
```

**Comment by vsmalladi** [comment]
So we can update status like this
 and maybe use the set_status_down = []  and set_status_up = [] to work on consent to biospecimen and genomics
