### ISSUE TITLE
Filter Demographics

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#50]
+Age at Diagnosis
        20-39
        40-59
        60-79
        80+
    +Gender
        Male
        Female
    +Ethnicity
        Hispanic
        Non-Hispanic
    +Race
        American Indian
        Asian
        Black
        Hawaiian Pacific Islander
        White
    +Vital Status
        Alive
        Dead

**Comment by mingjiecn** [comment]
Add 0 - 19 to +Age at Diagnosis.  Change Dead to Deceased in +Vital Status
