### ISSUE TITLE
Surgery Filter

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#51]
+Surgery Location
        UTSW
        Outside
    +Surgery Type
        No Surgery (conceptcd=5)
        Radioablation (conceptcd=2)
        Partial Nephrectomy (conceptcd=1)
        Total Nephrectomy (conceptcd=0)
        Metastasectomy (conceptcd=4)
    +Procedure Method
        Laparoscopic Surgery (laparoscopic=1)
        Robotic Assisted Surgery (roboticassisted=1)

**Comment by SenseCode** [comment]
What the conceptcd means? Are these for the indexing facets?
