### ISSUE TITLE
Biometrics and Blood Work 

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#52]
+ Within 30 days prior to Date of Surgery (from vital_labs_surgery_view)
        + Biometric Parameters
            +**BMI**
                Underweight (<18.5) : select distinct(patientid) from vital_labs where surgery_date_diff<=30 AND surgery_date_diff>0 AND conceptcd=1 AND value<18.5 order by surgery_date_diff asc;
                Normal (18.5-24.9) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=1 AND value>=18.5 AND value<=24.9;
                Overweight (25-29.9) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=1 AND value>=25 AND value<=29.9;
                Obese (>30) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=1 AND value>=30;
            +**BP_Systolic**
                Normal (Below 120 mmHg) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=3 AND value<=120;
                PreHypertension (121 - 139) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=3 AND value>=121 AND value<=139;
                Hypertension (Above 140) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=3 AND value>=140 AND value<=159;
            +**BP_Diastolic**
                Normal (Below 80 mmHg) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=2 AND value<=80;
                PreHypertension (81 - 89) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=2 AND value>=81 AND value<=89;
                Hypertension (Above 90) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=2 AND value>=90 AND value<=99;
        + Basic Blood Work 
            +**Hemoglobin**
                Below : select distinct(patientid) from vital_labs_surgery_view where conceptcd=9 AND value<12.4;
                Normal (12.4-17.3 g/dL) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=9 AND value>=12.4 AND value<=17.3;
                Above : select distinct(patientid) from vital_labs_surgery_view where conceptcd=9 AND value>17.3;
            +**Platelets**
                Below : select distinct(patientid) from vital_labs_surgery_view where conceptcd=12 AND value<140;
                Normal Range (140-450 10^3/ul): select distinct(patientid) from vital_labs_surgery_view where conceptcd=12 AND value>=140 AND value<=450;
                Above : select distinct(patientid) from vital_labs_surgery_view where conceptcd=12 AND value>450;
            +**WBC**
                Below : select distinct(patientid) from vital_labs_surgery_view where conceptcd=14 AND value<4;
                Normal Range (4-11 10^3/ul) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=14 AND value>=4 AND value<=11;
                Above : select distinct(patientid) from vital_labs_surgery_view where conceptcd=14 AND value>11;
            +**Neutrophils**
                Below : select distinct(patientid) from vital_labs_surgery_view where conceptcd=11 AND value<1.5;
                Normal Range (1.5-7.4 10^3/ul) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=11 AND value>=1.5 AND value<=7.4;
                Above : select distinct(patientid) from vital_labs_surgery_view where conceptcd=11 AND value>7.4;
            +**Creatinine**
                Below : select distinct(patientid) from vital_labs_surgery_view where conceptcd=8 AND value<0.67;
                Normal Range (0.67-1.17 mg/dL) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=8 AND value>=0.67 AND value<=1.17;
                Above : select distinct(patientid) from vital_labs_surgery_view where conceptcd=8 AND value>1.17;
            +**Calcium** 
                Below : select distinct(patientid) from vital_labs_surgery_view where conceptcd=7 AND value<8.8;
                Normal Range (8.8-10.2 mg/dL) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=7 AND value>=8.8 AND value<=10.2;
                Above : select distinct(patientid) from vital_labs_surgery_view where conceptcd=7 AND value>10.2;
            +**Albumin**
                Below : select distinct(patientid) from vital_labs_surgery_view where conceptcd=6 AND value<3.5;
                Normal Range (3.5-5.2 g/dL) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=6 AND value>=3.5 AND value<=5.2;
                Above : select distinct(patientid) from vital_labs_surgery_view where conceptcd=6 AND value>5.2;
            +**Sodium**
                Below : select distinct(patientid) from vital_labs_surgery_view where conceptcd=13 AND value<135;
                Normal Range (135-145 mmol/L) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=13 AND value>=135 AND value<=145;
                Above : select distinct(patientid) from vital_labs_surgery_view where conceptcd=13 AND value>145;
            +**LDE**
                Below : select distinct(patientid) from vital_labs_surgery_view where conceptcd=10 AND value<135;
                Normal Range (135-225 U/L) : select distinct(patientid) from vital_labs_surgery_view where conceptcd=10 AND value>=135 AND value<=225;
                Above  : select distinct(patientid) from vital_labs_surgery_view where conceptcd=10 AND value>225;
    
    + Within 30 days prior to Line One Therapy (from vital_labs_line1_view)
        + Same as Above
    + Within 30 days prior to Line Two Therapy
        + Same as Above
    + Within 30 days prior to Line Three Therapy
        + Same as Above
    + Within 30 days prior to Line Four Therapy
        + Same as Above

**Comment by vsmalladi** [comment]
Most recent value Within 30 days prior to Date of Nephrectomy 

- BMI
 Underweight (<18.4) : 
 Normal (18.5-24.9) 
 Overweight (25-29.9) 
 Obese (>30)

- BP_Systolic
  Normal (Below 120 mmHg)
  PreHypertension (121 - 139) 
  Hypertension (Above 140) 

- BP_Diastolic
    Normal (Below 80 mmHg) 
    PreHypertension (81 - 89) 
    Hypertension (Above 90)

- Hemoglobin
     Below (9-12.3)
     Normal (12.4-17.3 g/dL) 
     Above (Above 17.4) 

- Platelets
   Below (12-140)
   Normal Range (140-450 10^3/ul): 
   Above (Above 450)

- WBC
    Below (3.9) : 
    Normal Range (4-10.9 10^3/ul)
    Above (Above 11)

- Neutrophils
                Below (1.4) 
                Normal Range (1.5-7.3 10^3/ul) 
                Above ( Above 7.4)

- Creatinine
                Below (0.66)
                Normal Range (0.67-1.16 mg/dL) 
                Above (Above 1.17) 

- Calcium 
                Below (8.7)
                Normal Range (8.8-10.1 mg/dL)
                Above (Above 10.2)
- Albumin
                Below (3.4) 
                Normal Range (3.5-5.2 g/dL) 
                Above (5.3)

- Sodium
                Below (134)
                Normal Range (135-145 mmol/L) 
                Above (146)

  - LDH
                Below  (134)
                Normal Range (135-225 U/L) 
                Above (225)

**Comment by mingjiecn** [comment]
1. Need to modify the test data
2. Do we need to add one filter for "Not available"? @vsmalladi 
3. The filter format is not consistent.  For example Above (Above 10.2) in Calcium and Above (5.3) in Albumin and Obese (>30) in BMI.

**Comment by vsmalladi** [comment]
Yes let’s add a filter not available.

For obsess should be Above as well. All filter should be inclusive of the number mentioned as in >= or <=.

**Comment by mingjiecn** [comment]
![image](https://user-images.githubusercontent.com/44071821/101674094-aadced00-3a1d-11eb-9b23-434818f0754c.png)

![image](https://user-images.githubusercontent.com/44071821/101673611-065aab00-3a1d-11eb-8eaf-1a996bf02263.png)
![image](https://user-images.githubusercontent.com/44071821/101673690-1c686b80-3a1d-11eb-8bb3-c0d1974e1be7.png)

**Comment by vsmalladi** [comment]
Actuall ranges are in partahtesis 
- BMI
 Underweight (< 18.5) : 
 Normal (18.5>= and < 25) 
 Overweight (25 >= and < 30) 
 Obese (>= 30)

- BP_Systolic
  Normal (< 121)
  PreHypertension (121 >= and  <140 ) 
  Hypertension (>= 140 ) 

- BP_Diastolic
    Normal (< 81) 
    PreHypertension (81 >= and < 90) 
    Hypertension ( >= 90)

- Hemoglobin
     Below (>= 9 and < 12.4)
     Normal (12.4>= and <17.4) 
     Above (17.4 >= ) 

- Platelets
   Below (12>= and < 141)
   Normal Range (141>= and < 451 10^3/ul): 
   Above (451 >= )

- WBC
    Below (< 4) : 
    Normal Range (4 >= and < 11)
    Above (11 >= )

- Neutrophils
                Below (< 1.5) 
                Normal Range (1.5 >= and <7.4) 
                Above (  7.4 >= )

- Creatinine
                Below (< 0.67)
                Normal Range (0.67>= and <1.17 ) 
                Above (1.17 >=) 

- Calcium 
                Below (< 8.8)
                Normal Range (8.8 >= and < 10.2)
                Above (10.2 >=)
- Albumin
                Below (< 3.5) 
                Normal Range (3.5 >= and < 5.3 ) 
                Above (5.3 >= )

- Sodium
                Below (< 135)
                Normal Range (135>= and <146) 
                Above (146 >= )

  - LDH
                Below  (< 135)
                Normal Range (135>= and <226) 
                Above (226>=)

**Comment by mingjiecn** [comment]
updated the range value:
![image](https://user-images.githubusercontent.com/44071821/101988891-42328200-3c62-11eb-944d-0543c98bf0c6.png)
![image](https://user-images.githubusercontent.com/44071821/101988900-4bbbea00-3c62-11eb-98ac-c1a9d4faabf2.png)
