### ISSUE TITLE
AJCC TNM Stage Filter

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#60]
+pT 6th edition
        1A
        1B
        2
        3
        3A
        3B
        3C
        4
    +pT 7th edition
        1A
        1B
        2A
        2B
        3A
        3B
        3C
    +pN
        pN0
        pN1

    +TNM Stage 6th edition
        1
        2
        3
        4
        
    +TNM Stage 7th (Composite)
        1
        2
        3
        4

**Comment by SenseCode** [comment]
We should make sure with user again, to use pT-stage or AJCC-pT-stage for T-stage? Both do not have pN stage. Should we add pN in facets?

**Comment by vsmalladi** [comment]
Already implemented
