### ISSUE TITLE
Dataset/Experiment linkages

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#69]

**Comment by SenseCode** [comment]
I will update all the issues related to experiment part step by step here:
Need rewrite biospecimen schema for linking to bioexperiment with biospecimen details, will prepare the related test inserts according to these changes.
Concerns: 
a. Organism/species: human, mouse?
b.biosample type:"Blood","Fluid", "Tissue", "Molecule"?
c. sub_sample_type with dependencies: should we put FFPE and FF here? (check the below figures)
d. treatments: any other type except drug treatment and radiation? Should we set a separate treatment schema and link to categorized taxon_id? Should we set up treatment_time, and treatment_concentration in other schema or just here if only two categories?

e. host sample: is there any or not?
f. donor sample: is there any or not?
g. missing keyword: cell line, FFPE, FF, xenograft. Where we should fit them and what's the related fields? 
h. preservative_type: DMSO, none. So DMSO is not a processing type?
I. need add freeze/thaw cycles.(This is important for researcher related to genomic results with sample quality).
I. pool_of, part_of, original_of samples?
J. Any other fields except the current schema ? (Which should be shown in biospecimen and bio-experiment)?
![image](https://user-images.githubusercontent.com/38848214/86562185-db2cd680-bf27-11ea-89d0-17244c6d8060.png)
![image](https://user-images.githubusercontent.com/38848214/86562195-e122b780-bf27-11ea-9468-fc026ecd4dd3.png)
